- name: Instalacao Jenkins
  hosts: server-devops

  tasks:   
  - name: Instalacao pre-requisito JAVA
    package: name=java state=latest
 
  
  - name: instalacao wget
    package: name=wget state=latest

  
  - name: atualiza repo jenkins
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo 
    dest: /etc/yum.repos.d/jenkins.repo 

  
  - name: baixar key
    rpm_key: 
     state: present
     key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

  
  - name: instalacao jenkins
    package: name=jenkins state=latest

  
  - name: liberacao firewall
    firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled

  
  - name: reiniciar firewall
    service:
       name: firewalld
       state: restarted

  
  - name: start jenkins
    service:
       name: jenkins
       state: restarted
