- name: Install Terraform
  hosts: server-devops
  
  tasks:
    - name: Download terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
        dest: /root/terraform_1.0.11_linux_amd64.zip

    - name: Install Unzip
      yum:
        name: unzip
        state: latest

    - name: Unzip terraform
      unarchive:
        src: /root/terraform_1.0.11_linux_amd64.zip
        dest: /root/
        remote_src: yes

    - name: Copy terraform to path
      copy:
        src: /root/terraform
        dest: /usr/bin/terraform
        remote_src: yes
